version: '3'

services:
  mysql8:
    container_name: stock.mysql8
#    platform: linux/x86_64
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - ./mysql/storage:/var/lib/mysql
      - ./mysql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  core-service:
    container_name: stock.core-service
    build:
      context: ./
      dockerfile: core-service/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./..:/var/www:delegated
